services:
  horizon-game-server:
    image: 127.0.0.1:5000/horizon-game-server:latest
    ports:
      - target: 3000
        published: 3000
        mode: host
      - target: 3001
        published: 3001
        mode: host
    environment:
      - RUST_LOG=info
    networks:
      - horizon-network
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  memory-db-data:

networks:
  horizon-network:
    driver: overlay
    attachable: true

secrets:
  db_password:
    external: true