[npm]
dashboard_path = "./Horizon-Dashboard"

[deployment]
hosts = [
  { address = "localhost", username = "myuser", auth_method = { Password = "mypassword" } },
  { address = "gameplexsoftware.com", username = "myuser", auth_method = { Password = "mypassword" }, ssh_port = 22 }
]

[docker]
containers = [
  { image_name = "nginx:latest", container_name = "horizon-game-server" },
  { image_name = "nginx:latest", container_name = "horizon-game-database" },
  { image_name = "nginx:latest", container_name = "horizon-game-cache" }
]