[npm]
dashboard_path = "./Horizon-Dashboard"

[deployment]
hosts = [
  { address = "localhost", username = "tristan", auth_method = { Password = "1261" } },
  { address = "gameplexsoftware.com", username = "fbadmin", auth_method = { Password = "fbadmin" }, ssh_port = 8789 }
]

[docker]
containers = [
  { image_name = "nginx:latest", container_name = "horizon-game-server" },
  { image_name = "nginx:latest", container_name = "horizon-game-database" },
  { image_name = "nginx:latest", container_name = "horizon-game-cache" }
]