# registry-compose.yml
version: '3.8'

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - registry-data:/var/lib/registry

volumes:
  registry-data: